In [146]:
# Import Necessary Libraries
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns


%matplotlib inline

In [147]:
df = pd.read_csv("D:\Project amity/customer_query.csv")
df.head()

Interaction Number  Date of Interaction   Account number   Issue  \
0            100102013           10-01-2014     1.009659e+10      8   
1            100102014           10-01-2014     5.291498e+10      4   
2            100102015           10-01-2014     3.163961e+10      6   
3            100102016           10-01-2014     1.598096e+10     10   
4            100102017           10-01-2014     9.652346e+10      1   

                                     Issue in detail   AHT Churn  
0                                    Screen damaged   20.0   Yes  
1                                     Dropped calls   40.0   Yes  
2                     Need a cheaper unlimited plan   50.0    No  
3                            Upgrade to a new phone   37.0    No  
4  Unlock device so that it can used on a differe...  22.0   Yes

In [148]:
df.tail()

Interaction Number  Date of Interaction   Account number   Issue  \
245            100102263           10-07-2014     1.750000e+11      7   
246            100102264           10-07-2014     1.760000e+11      9   
247            100102265           10-07-2014     1.770000e+11      5   
248            100102266           10-07-2014     1.780000e+11      2   
249            100102267           10-07-2014     1.854214e+10      5   

                      Issue in detail    AHT Churn  
245  need to check call and text logs  20.55   Yes  
246     Charges to cancel my account   20.55   Yes  
247                 payment extension  12.45   Yes  
248      Apps to backup text message   20.55   Yes  
249                 payment extension  10.52   Yes

In [149]:
df.loc[df.Churn=='No','Churn']=0
df.loc[df.Churn=='Yes','Churn']=1

In [150]:
df.head()

Interaction Number  Date of Interaction   Account number   Issue  \
0            100102013           10-01-2014     1.009659e+10      8   
1            100102014           10-01-2014     5.291498e+10      4   
2            100102015           10-01-2014     3.163961e+10      6   
3            100102016           10-01-2014     1.598096e+10     10   
4            100102017           10-01-2014     9.652346e+10      1   

                                     Issue in detail   AHT Churn  
0                                    Screen damaged   20.0     1  
1                                     Dropped calls   40.0     1  
2                     Need a cheaper unlimited plan   50.0     0  
3                            Upgrade to a new phone   37.0     0  
4  Unlock device so that it can used on a differe...  22.0     1

In [151]:
df.tail()

Interaction Number  Date of Interaction   Account number   Issue  \
245            100102263           10-07-2014     1.750000e+11      7   
246            100102264           10-07-2014     1.760000e+11      9   
247            100102265           10-07-2014     1.770000e+11      5   
248            100102266           10-07-2014     1.780000e+11      2   
249            100102267           10-07-2014     1.854214e+10      5   

                      Issue in detail    AHT Churn  
245  need to check call and text logs  20.55     1  
246     Charges to cancel my account   20.55     1  
247                 payment extension  12.45     1  
248      Apps to backup text message   20.55     1  
249                 payment extension  10.52     1

In [152]:
df.dtypes

Interaction Number        int64
Date of Interaction      object
Account number          float64
Issue                     int64
Issue in detail          object
AHT                     float64
Churn                    object
dtype: object

In [153]:
new_df =df[['Issue','Churn']]
X=np.array(df['Issue']).astype('int').reshape(-1,1)
y=np.array(df['Churn']).astype('int').reshape(-1,1)
print(X[0:5])
print(y[:5])

[[ 8]
 [ 4]
 [ 6]
 [10]
 [ 1]]
[[1]
 [1]
 [0]
 [0]
 [1]]


In [24]:
###Divide the data as TRAIN and Test

In [154]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test= train_test_split(X,y,test_size=0.5,random_state=1)
print(X_train.shape,y_train.shape,X_test.shape,y_test.shape)

(125, 1) (125, 1) (125, 1) (125, 1)


In [ ]:
# Machine learning libraries ( we will used different model and see which gives more accurate result )

In [155]:
# Machine Learning classification model libraries
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn import metrics


In [ ]:
#LOGISTIC REGRESSION MODEL

In [117]:
logmodel=LogisticRegression(random_state=50)
logmodel.fit(X_train,y_train)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


LogisticRegression(random_state=50)

In [156]:
pred=logmodel.predict(X_test)

In [157]:
logmodel_accuracy = round(metrics.accuracy_score(y_test, pred) * 100, 2)

In [158]:
#Fit the Support Vector Machine Model
svcmodel = SVC(kernel='linear', random_state=50, probability=True)
svcmodel.fit(X_train,y_train)

#Predict the value for new, unseen data
svc_pred = svcmodel.predict(X_test)

# Find Accuracy using accuracy_score method
svc_accuracy = round(metrics.accuracy_score(y_test, svc_pred) * 100, 2)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


In [159]:
#Fit the K-Nearest Neighbor Model
from sklearn.neighbors import KNeighborsClassifier
knnmodel = KNeighborsClassifier(n_neighbors=5, metric='minkowski', p=2) #p=2 represents Euclidean distance, p=1 represents Manhattan Distance
knnmodel.fit(X_train, y_train) 
  
#Predict the value for new, unseen data
knn_pred = knnmodel.predict(X_test)

# Find Accuracy using accuracy_score method
knn_accuracy = round(metrics.accuracy_score(y_test, knn_pred) * 100, 2)


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:179: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


In [160]:
#Fit the Decision Tree Classification Model
from sklearn.tree import DecisionTreeClassifier
dtmodel = DecisionTreeClassifier(criterion = "gini", random_state = 50)
dtmodel.fit(X_train, y_train) 
  
#Predict the value for new, unseen data
dt_pred = dtmodel.predict(X_test)

# Find Accuracy using accuracy_score method
dt_accuracy = round(metrics.accuracy_score(y_test, dt_pred) * 100, 2)

In [161]:
#Fit the Random Forest Classification Model
from sklearn.ensemble import RandomForestClassifier
rfmodel = RandomForestClassifier(n_estimators = 100, criterion = 'entropy', random_state = 0)
rfmodel.fit(X_train, y_train) 
  
#Predict the value for new, unseen data
rf_pred = rfmodel.predict(X_test)

# Find Accuracy using accuracy_score method
rf_accuracy = round(metrics.accuracy_score(y_test, rf_pred) * 100, 2)

C:\Users\srini\AppData\Local\Temp/ipykernel_12500/3498443462.py:4: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  rfmodel.fit(X_train, y_train)


In [162]:
# Compare Several models according to their Accuracies
Model_Comparison = pd.DataFrame({
    'Model': ['Logistic Regression', 'Support Vector Machine', 'K-Nearest Neighbor', 
              'Decision Tree', 'Random Forest'],
    'Score': [logmodel_accuracy, svc_accuracy, knn_accuracy, 
              dt_accuracy, rf_accuracy]})
Model_Comparison_df = Model_Comparison.sort_values(by='Score', ascending=False)
Model_Comparison_df = Model_Comparison_df.set_index('Score')
Model_Comparison_df.reset_index()

Score                   Model
0   79.2           Decision Tree
1   79.2           Random Forest
2   71.2      K-Nearest Neighbor
3   58.4     Logistic Regression
4   46.4  Support Vector Machine

In [163]:
#Confusion matrix for decision  model
from sklearn.metrics import confusion_matrix
conf_mat_dtmodel=confusion_matrix(y_test,pred)
conf_mat_dtmodel

array([[73,  0],
       [52,  0]], dtype=int64)

In [164]:
##Save MI Model
import joblib
joblib.dump(dtmodel,"customer_churn_risk_predictor_model.pkl")

['customer_churn_risk_predictor_model.pkl']

In [165]:
Churn_model=joblib.load("customer_churn_risk_predictor_model.pkl")

In [166]:
a=["1:billing","2=device","3:International Plan","4:Network","5:Payment","6:Plan",
   "7:Registration","8:Reapir","9:Save","10:Upgrade"]

In [167]:
print (a)

['1:billing', '2=device', '3:International Plan', '4:Network', '5:Payment', '6:Plan', '7:Registration', '8:Reapir', '9:Save', '10:Upgrade']


In [203]:
a=[[4]]

In [204]:
print (a)

[[4]]


In [205]:
print (a)

[[4]]


In [206]:
Churn_model.predict(a)

array([1])

In [207]:
prediction=Churn_model.predict(a)

In [208]:
prediction

array([1])

In [209]:
if prediction[0] == 1:
  print('Churn Risk is high')
else:
  print('Churn Risk is low')
 

Churn Risk is high
